services:
     ress:
        image: ress:local
        container_name: ress
        volumes:
            - ./ress:/root/.local/share/ress/hoodi
            - ./jwttoken:/root/jwt:ro
        ports:
            - 127.0.0.1:6060:6060 # metrics
            - 127.0.0.1:8551:8551 # engine rpc
            - 30303:30303/tcp # execution p2p, open to internet
            - 30303:30303/udp # execution p2p, open to internet
        tty: true
        restart: on-failure
        command: >
          --port 30303
          --chain hoodi
          --authrpc.jwtsecret /root/jwt/jwt.hex
          --authrpc.addr 0.0.0.0
          --authrpc.port 8551
          --metrics 0.0.0.0:6060
          --trusted-peers "enode://fe688fdc85454231ff3c9442775ca64d637f3a262b3f105ccb4a579f21618f7b757cec1dc19b8759460b89ef513a51375832f66a6a4872e0fc4088d5d4c0dff3@16.170.210.245:30303"
    
     consensus:
        image: sigp/lighthouse:latest
        container_name: beacon
        tty: true
        restart: on-failure
        volumes:
            - ./lighthouse:/root/.lighthouse
            - ./jwttoken:/root/jwt:ro
        ports:
            - 127.0.0.1:5052:5052 # consensus http
            - 127.0.0.1:5054:5054 # metrics http
            - 9000:9000/tcp # consensus p2p, open to internet
            - 9000:9000/udp # consensus p2p, open to internet
        command: >
          lighthouse
          --debug-level info
          --network hoodi
          beacon_node
          --datadir /root/.lighthouse/hoodi
          --target-peers 120
          --disable-upnp
          --http
          --http-address 0.0.0.0
          --http-allow-origin *
          --metrics
          --metrics-address 0.0.0.0
          --metrics-allow-origin *
          --validator-monitor-auto
          --execution-jwt /root/jwt/jwt.hex
          --execution-endpoints http://ress:8551
          --checkpoint-sync-url https://checkpoint-sync.hoodi.ethpandaops.io