services:
    ress:
        image: ress:local
        container_name: ress
        volumes:
            - ./ress:/root/.local/share/ress/hoodi
            - ./jwttoken:/root/jwt:ro
        ports:
            - 127.0.0.1:6060:6060 # metrics
            - 127.0.0.1:8551:8551 # engine rpc
            - 30303:30303/tcp # execution p2p, open to internet
            - 30303:30303/udp # execution p2p, open to internet
        tty: true
        restart: on-failure
        command: >
          --port 30303
          --authrpc.jwtsecret /root/jwt/jwt.hex
          --authrpc.addr 0.0.0.0
          --authrpc.port 8551
          --metrics 0.0.0.0:6060
          --trusted-peers "enode://04bcda1f0a750ce5fd986187825ffcd7aa1ad3641027f646707c2121443e85ae309e047f228c0067aac382f0c0cab21e91a2852e10b4f7724187b0185bb78b2b@100.126.2.26:30303, enode://04e4e548eee6f042685ad0b6793de36a4c5c6a3107cdf54cbfeedbeb0df4138d4c65b534fb700072341098644eb5a6b125e63c36464d8f57c19b6e26ca36ae7c@100.75.245.88:30303, enode://2c464310c41c2a9d7be44783d38ab2b8517e4c5133719de1a4b605294cfd201f33b2c5b4158054b171a3ba26837f85a97f6a8553622ea1033d70c98fc1b70fa0@69.67.151.138:30303, enode://065cffdc5c824d42c23f933ca615daad8b887f2330b1313e8c1a5d850be93d3b6e95698d4f774bbf7b2639ac6d6d870645156eeb805bd3448107806cc0a6e5f9@69.67.151.138:30303"
    
    consensus:
        image: sigp/lighthouse:latest
        container_name: beacon
        tty: true
        restart: on-failure
        volumes:
            - ./lighthouse:/root/.lighthouse
            - ./jwttoken:/root/jwt:ro
        ports:
            - 127.0.0.1:5052:5052 # consensus http
            - 127.0.0.1:5054:5054 # metrics http
            - 9000:9000/tcp # consensus p2p, open to internet
            - 9000:9000/udp # consensus p2p, open to internet
        command: >
          lighthouse
          --debug-level info
          --network hoodi
          beacon_node
          --datadir /root/.lighthouse/hoodi
          --target-peers 120
          --disable-upnp
          --http
          --http-address 0.0.0.0
          --http-allow-origin *
          --metrics
          --metrics-address 0.0.0.0
          --metrics-allow-origin *
          --validator-monitor-auto
          --execution-jwt /root/jwt/jwt.hex
          --execution-endpoints http://ress:8551
          --checkpoint-sync-url https://checkpoint-sync.hoodi.ethpandaops.io